version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0  # Chọn phiên bản phù hợp
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Tắt bảo mật nếu bạn không cần
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Điều chỉnh bộ nhớ nếu cần
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9222:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601

volumes:
  data01:
    driver: local